import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, Show, SignIn, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Toaster } from 'sonner';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="">

          

            <Show when="signed-out">
              <section className="flex justify-center items-center p-4 ">
              <SignIn />
              </section>
            </Show>

          
          <Show when="signed-in">
            {children}
            <Toaster position="top-right" richColors />
          </Show>
        </body>
      </html>
    </ClerkProvider>
  );
}
